openapi: 3.1.0
info:
  title: Sunny Agent - 对话历史与用户管理 API
  version: 1.0.0
  description: 用户认证、对话管理和用户管理相关的 API 接口

servers:
  - url: http://localhost:8008
    description: Development server

paths:
  # ========== Authentication ==========
  /api/auth/login:
    post:
      summary: 用户登录
      tags: [Authentication]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginRequest'
      responses:
        '200':
          description: 登录成功
          headers:
            Set-Cookie:
              schema:
                type: string
                example: access_token=eyJ...; HttpOnly; Path=/; Max-Age=86400
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/LoginResponse'
        '401':
          description: 用户名或密码错误
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 账户已被禁用
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/auth/logout:
    post:
      summary: 用户退出登录
      tags: [Authentication]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 退出成功
          headers:
            Set-Cookie:
              schema:
                type: string
                example: access_token=; HttpOnly; Path=/; Max-Age=0
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Logged out successfully

  /api/auth/me:
    get:
      summary: 获取当前登录用户信息
      tags: [Authentication]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 当前用户信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '401':
          description: 未登录或会话已过期
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ========== Conversations ==========
  /api/conversations:
    get:
      summary: 获取当前用户的对话列表
      tags: [Conversations]
      security:
        - cookieAuth: []
      parameters:
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 100
        - name: offset
          in: query
          schema:
            type: integer
            default: 0
      responses:
        '200':
          description: 对话列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  conversations:
                    type: array
                    items:
                      $ref: '#/components/schemas/ConversationSummary'
                  total:
                    type: integer

    post:
      summary: 创建新对话
      tags: [Conversations]
      security:
        - cookieAuth: []
      responses:
        '201':
          description: 对话创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'

  /api/conversations/{id}:
    get:
      summary: 获取对话详情
      tags: [Conversations]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 对话详情
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: 对话不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    patch:
      summary: 更新对话标题
      tags: [Conversations]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  maxLength: 50
              required:
                - title
      responses:
        '200':
          description: 更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Conversation'
        '404':
          description: 对话不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    delete:
      summary: 删除对话
      tags: [Conversations]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 删除成功
        '404':
          description: 对话不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  # ========== User Management (Admin Only) ==========
  /api/users:
    get:
      summary: 获取所有用户列表
      tags: [User Management]
      security:
        - cookieAuth: []
      responses:
        '200':
          description: 用户列表
          content:
            application/json:
              schema:
                type: object
                properties:
                  users:
                    type: array
                    items:
                      $ref: '#/components/schemas/UserInfo'
        '403':
          description: 无权限（需要管理员）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

    post:
      summary: 创建新用户
      tags: [User Management]
      security:
        - cookieAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserRequest'
      responses:
        '201':
          description: 用户创建成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: 用户名已存在或格式无效
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 无权限（需要管理员）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/users/{id}:
    delete:
      summary: 删除用户
      tags: [User Management]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        '204':
          description: 删除成功
        '400':
          description: 无法删除（最后一个管理员或自己）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 无权限（需要管理员）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '404':
          description: 用户不存在
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /api/users/{id}/status:
    patch:
      summary: 更新用户状态（启用/禁用）
      tags: [User Management]
      security:
        - cookieAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                status:
                  type: string
                  enum: [active, disabled]
              required:
                - status
      responses:
        '200':
          description: 状态更新成功
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserInfo'
        '400':
          description: 无法禁用（最后一个管理员或自己）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '403':
          description: 无权限（需要管理员）
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

components:
  securitySchemes:
    cookieAuth:
      type: apiKey
      in: cookie
      name: access_token

  schemas:
    LoginRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
        password:
          type: string
          minLength: 1
      required:
        - username
        - password

    LoginResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/UserInfo'
        message:
          type: string
          example: Login successful

    UserInfo:
      type: object
      properties:
        id:
          type: string
          format: uuid
        username:
          type: string
        role:
          type: string
          enum: [admin, user]
        status:
          type: string
          enum: [active, disabled]
        created_at:
          type: string
          format: date-time

    CreateUserRequest:
      type: object
      properties:
        username:
          type: string
          minLength: 3
          maxLength: 20
          pattern: '^[a-zA-Z][a-zA-Z0-9_]*$'
        password:
          type: string
          minLength: 1
        role:
          type: string
          enum: [admin, user]
          default: user
      required:
        - username
        - password

    ConversationSummary:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        updated_at:
          type: string
          format: date-time

    Conversation:
      type: object
      properties:
        id:
          type: string
        thread_id:
          type: string
        title:
          type: string
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      properties:
        detail:
          type: string
          example: Error message here
